# Generated by Django 2.2.13 on 2020-08-16 17:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bio',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='vendor',
            name='image',
            field=models.ImageField(blank=True, default='vendor_placeholder.jpg', null=True, upload_to=accounts.models.get_image_filename, verbose_name='vendor_image'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
