# Generated by Django 2.2.13 on 2020-08-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_categories_category_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='top_category',
            field=models.BooleanField(default=False),
        ),
    ]
