# Generated by Django 2.2.13 on 2020-08-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_category_top_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', unique=True),
        ),
    ]
