# Generated by Django 2.2.13 on 2020-08-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20200819_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', null=True, unique=True),
        ),
    ]
