# Generated by Django 2.2.13 on 2020-08-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_auto_20200819_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='product_image', to='shops.Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_categories',
            field=models.ManyToManyField(blank=True, to='shops.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
