# Generated by Django 2.2.13 on 2020-08-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_auto_20200820_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
